### ISSUE TITLE
i cant run the process

### ISSUE THREAD

**Issue by nianchu1** [wyhuai/DDNM#2]
Dear authors,

when i run  **python main.py --ni --simplified --config celeba_hq.yml --path_y celeba_hq --eta 0.85 --deg "sr_averagepooling" --deg_scale 4.0 --sigma_y 0 -i demo**
it stacks!
er message :
  File "X:\game\DDNM-main\main.py", line 166, in main
    runner.sample(args.simplified)
  File "X:\game\DDNM-main\guided_diffusion\diffusion.py", line 200, in sample
    self.simplified_ddnm_plus(model, cls_fn)
  File "X:\game\DDNM-main\guided_diffusion\diffusion.py", line 302, in simplified_ddnm_plus
    for x_orig, classes in pbar:
  File "X:\python\Anaconda\envs\game\lib\site-packages\tqdm\std.py", line 1195, in __iter__
    for obj in iterable:
  File "X:\python\Anaconda\envs\game\lib\site-packages\torch\utils\data\dataloader.py", line 435, in __iter__
    return self._get_iterator()
  File "X:\python\Anaconda\envs\game\lib\site-packages\torch\utils\data\dataloader.py", line 381, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "X:\python\Anaconda\envs\game\lib\site-packages\torch\utils\data\dataloader.py", line 1034, in __init__
    w.start()
  File "X:\python\Anaconda\envs\game\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "X:\python\Anaconda\envs\game\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "X:\python\Anaconda\envs\game\lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
  File "X:\python\Anaconda\envs\game\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "X:\python\Anaconda\envs\game\lib\multiprocessing\reduction.py", line 61, in dump
    pickle.dump(obj, file, protocol)
AttributeError: Can't pickle local object 'Diffusion.simplified_ddnm_plus.<locals>.seed_worker'

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "X:\python\Anaconda\envs\game\lib\multiprocessing\spawn.py", line 107, in spawn_main
    new_handle = reduction.duplicate(pipe_handle,
  File "X:\python\Anaconda\envs\game\lib\multiprocessing\reduction.py", line 79, in duplicate
    return _winapi.DuplicateHandle(
OSError: [WinError 6] 句柄无效。

(game) X:\game\DDNM-main>
(game) X:\game\DDNM-main>
(game) X:\game\DDNM-main>python main.py --ni  --config celeba_hq.yml --path_y celeba_hq --eta 0.85 --deg "sr_averagepooling" --deg_scale 4.0 --sigma_y 0 -i demo
INFO - main.py - 2022-12-06 12:28:28,418 - Using device: cuda
Run SVD-based DDNM. 100 sampling steps. travel_length = 1, travel_repeat = 1. Task: sr_averagepooling.
Dataset has size 8
X:\python\Anaconda\envs\game\lib\site-packages\torch\utils\data\dataloader.py:554: UserWarning: This DataLoader will create 32 worker processes in total. Our suggested max number of worker in current system is 12 (`cpuset` is not taken into account), which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
Start from 0
  0%|                                                                                            | 0/8 [00:00<?, ?it/s]
ERROR - main.py - 2022-12-06 12:28:36,459 - Traceback (most recent call last):
  File "X:\game\DDNM-main\main.py", line 166, in main
    runner.sample(args.simplified)
  File "X:\game\DDNM-main\guided_diffusion\diffusion.py", line 208, in sample
    self.svd_based_ddnm_plus(model, cls_fn)
  File "X:\game\DDNM-main\guided_diffusion\diffusion.py", line 537, in svd_based_ddnm_plus
    for x_orig, classes in pbar:
  File "X:\python\Anaconda\envs\game\lib\site-packages\tqdm\std.py", line 1195, in __iter__
    for obj in iterable:
  File "X:\python\Anaconda\envs\game\lib\site-packages\torch\utils\data\dataloader.py", line 435, in __iter__
    return self._get_iterator()
  File "X:\python\Anaconda\envs\game\lib\site-packages\torch\utils\data\dataloader.py", line 381, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "X:\python\Anaconda\envs\game\lib\site-packages\torch\utils\data\dataloader.py", line 1034, in __init__
    w.start()
  File "X:\python\Anaconda\envs\game\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "X:\python\Anaconda\envs\game\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "X:\python\Anaconda\envs\game\lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
  File "X:\python\Anaconda\envs\game\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "X:\python\Anaconda\envs\game\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'Diffusion.svd_based_ddnm_plus.<locals>.seed_worker'

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "X:\python\Anaconda\envs\game\lib\multiprocessing\spawn.py", line 107, in spawn_main
    new_handle = reduction.duplicate(pipe_handle,
  File "X:\python\Anaconda\envs\game\lib\multiprocessing\reduction.py", line 79, in duplicate
    return _winapi.DuplicateHandle(
OSError: [WinError 6] 句柄无效。

 i used the wrong python version???i have installed the required environment

**Comment by wyhuai** [comment]
It seems you are running on a Windows environment. What about set "num_workers: 32" in celeba_hq.yml as "num_workers: 1"? Anyway, if your environment can run guided-diffusion (https://github.com/openai/guided-diffusion), then our DDNM should be ok.

**Comment by nianchu1** [comment]
Thx.I'v set num_workers  32 to 0.it works well !
