### ISSUE TITLE
Should this work under Windows?

### ISSUE THREAD

**Issue by SoftologyPro** [wyhuai/DDNM#20]
Trying to run the first example after installing and downloading the model files...

```
  File "D:\Python\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'Diffusion.simplified_ddnm_plus.<locals>.seed_worker'

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Python\lib\multiprocessing\spawn.py", line 107, in spawn_main
    new_handle = reduction.duplicate(pipe_handle,
  File "D:\Python\lib\multiprocessing\reduction.py", line 79, in duplicate
    return _winapi.DuplicateHandle(
OSError: [WinError 6] The handle is invalid
```

**Comment by wyhuai** [comment]
You may refer to the closed issue "i cant run the process https://github.com/wyhuai/DDNM/issues/2"
