### ISSUE TITLE
不能运行demo

### ISSUE THREAD

**Issue by mafamily2496** [wyhuai/DDNM#6]
报下面的错误，是不是预训练的模型有问题？
ERROR - main.py - 2022-12-10 22:02:41,698 - Traceback (most recent call last):
  File "E:\project\py\DDNM\main.py", line 166, in main
    runner.sample(args.simplified)
  File "E:\project\py\DDNM\guided_diffusion\diffusion.py", line 138, in sample
    model.load_state_dict(torch.load(ckpt, map_location=self.device))
  File "D:\anaconda3\lib\site-packages\torch\serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "D:\anaconda3\lib\site-packages\torch\serialization.py", line 1020, in _legacy_load
    typed_storage._storage._set_from_file(
RuntimeError: unexpected EOF, expected 551739 more bytes. The file might be corrupted.

**Comment by wyhuai** [comment]
可能是没下载好

**Comment by manojkumar202** [comment]
Check if the model is placed in the exact directory as mentioned in the README file. I got the same error at first.
